name = "journal"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# Database configuration (D1)
# Uncomment and configure after creating database:
[[d1_databases]]
binding = "DB"
database_name = "journal-db2"
database_id = "e85aec07-9dbd-446c-9d1a-69ab746e2943"
